version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: exchange-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
#  redis:
#    image: redis:6-alpine
#    restart: always
#    container_name: exchange-redis
#    ports:
#      - 6379:6379
#    volumes:
#      - redis-data:/data
#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    container_name: exchange-redis-commander
#    ports:
#      - "8081:8081"
#    environment:
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#    depends_on:
#      - redis
volumes:
  mongo-data:
#  redis-data: